name = "kensan-instagram"
main = "src/index.js"
compatibility_date = "2026-06-07"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"

# 追加：画像を一時保存するR2バケットの設定
[[r2_buckets]]
binding = "IMAGE_BUCKET"
bucket_name = "kensan-images"
